name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to Datalake
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.2.1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "sa-east-1"

    - name: IaC cd
      run:
        cd "infra_iac"

    - name: terraform init
      env:
        COMMAND_IAC: terraform
      run:
        $COMMAND_IAC init

    - name: terraform validate
      env:
        COMMAND_IAC: terraform
      run:
        $COMMAND_IAC validate

    - name: terraform plan
      env:
        COMMAND_IAC: terraform
      run:
        $COMMAND_IAC plan

    - name: terraform apply
    env:
      COMMAND_IAC: terraform
    run:
      $COMMAND_IAC apply -auto-approve
